### PR TITLE
fix: renovate config cannot use private preset

### LINKED ISSUE #28: Action Required: Fix Renovate Configuration
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Error type: Cannot find preset's package (local>edgelaboratories/renovate-config:quant-engine)

### PR DESCRIPTION
**Pull request by antonioiubatti93**
- Closes #28 
- See https://github.com/renovatebot/renovate/discussions/9002

Aggregating the available private presets into a single one to start off with. We may use a public preset later on, if needed.

### CODE REVIEW

**Review by RemiMattheyDoret — COMMENTED** [review]
Isn't it mandatory for renovate to extend something? At least "config:base"? 🤷 
Is there a dashboard (an issue; explained [here](https://github.com/edgelaboratories/renovate-config#steps-to-test-a-configuration-locally) on how to build one) associated with the config presented in this PR?

**Comment by antonioiubatti93** [comment]
> Isn't it mandatory for renovate to extend something? At least "config:base"? shrug

I don't know. Will look into it (for example [the base config doesn't extend anything](https://github.com/edgelaboratories/renovate-config/blob/main/default.json), it seems). For sure I think I've deleted one excess line (the schema one)

> Is there a dashboard (an issue; explained [here](https://github.com/edgelaboratories/renovate-config#steps-to-test-a-configuration-locally) on how to build one) associated with the config presented in this PR?

I suppose this is [part of the config itself](https://github.com/edgelaboratories/calendar/pull/32/files#diff-f82f7d36a61d22f640c25bdb8b0435bf9cb38679d99d5f460753fa668ee7cdb3R2)

**Comment by antonioiubatti93** [comment]
@RemiMattheyDoret (/cc @sjiekak ):
- we're not obliged to extend any preset
- tried to perform several kinds of dry runs, even running renovate of the whole repo and open the dashboard: #34 . However, this was possible maybe just because I was using a github token of mine
- as short-term fix we may just barely copy the required config, until we get a public preset

**Review by RemiMattheyDoret — APPROVED** [review]
LGTM! I let you judge as to whether it is worth to wait for the approval of someone more knowledgeable (e.g. @sjiekak ).

**Review by sjiekak — APPROVED** [review]

**Pull request merged**
